name: hcs/auto_pr_approve

on:
  pull_request:

jobs:
  auto-pr-approve:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      pull-requests: write
      checks: read
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get associated pull request and approve it
        if: startsWith(github.event.pull_request.head.ref, 'hcs/create-erd-by-github-actions/')
        run: |
          PR=$(gh api repos/${{ github.repository }}/commits/${{ github.event.workflow_run.head_sha || github.sha }}/pulls | jq '.[0]')
          PR_NUM=$(echo $PR | jq '.number')
          gh pr merge $PR_NUM --merge --auto -R ${{ github.repository }}
          gh pr review $PR_NUM --approve -R ${{ github.repository }}
